version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80" # Vite serves on port 80 inside the container
    env_file:
      - .env
